name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: "8.6.3"
  
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Run deploy script
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NEXT_REWRITE_DOCS_URL: https://nextjs-basepath-rewrite-issue-docs.netlify.app/docs
        run: pnpm run deploy
  